// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9vQFn5K3rIAZShJ6bXOnV5PWl5_R3gtA',
    appId: '1:1044611157857:web:6744931fb894b52c0eff20',
    messagingSenderId: '1044611157857',
    projectId: 'flower-5809e',
    authDomain: 'flower-5809e.firebaseapp.com',
    storageBucket: 'flower-5809e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhDkFIPa5OklBg51TEEHSYm60pyzxjzUM',
    appId: '1:1044611157857:android:680d40702552137b0eff20',
    messagingSenderId: '1044611157857',
    projectId: 'flower-5809e',
    storageBucket: 'flower-5809e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBczu1BNoHg7Ec-BqfNKVnvR0jO5yjuHX0',
    appId: '1:1044611157857:ios:17c3b8d186dc9fdb0eff20',
    messagingSenderId: '1044611157857',
    projectId: 'flower-5809e',
    storageBucket: 'flower-5809e.appspot.com',
    iosBundleId: 'com.redaWork2032.aliHassan',
  );
}
